language: java
notifications:
  hipchat:
    rooms:
      secure: N+JcOvb7g8A8E7IL72RqIYRbwgyHJwA2QqyuskxoNrLmIcA9Rztc5IFdgOnhIkM3UNQ9AJH9aIr6hDDkHHxHc2oYNphmDzmhKgbiG6dM7Zu25jnMQtWroPEbqySzdk49QM8iLJ91L4kUwmWApd+1HRZLUxhFd3/xjtfRV1fzhtERZAs6Mx6z1qgsFWOxmZzfdQwhsuhQBkRxCKpfsWNYtBvID3eyl75/RQF6LhWzWpjKPXEaQkYoyDTSjTbZAmPz8q/llBerblh2E1bWP2HDo2cikoO8B9N5Y9T+oGb1HpbkgnE1izJOK0aZZLU1fBLjQYq5s0063MkJujunKLi2Td6xc/ha9u+/sC8ZNG8zHiLuI4Y/KHFQOXxK8xbSm1B/cK1klkulBRL/yI1mWfpRvDx+9fJ/HH3HihHWMBEfV/4Atx9gjDXYH5Sj0Yqw3buSfiooPO0pcsyTi/vEvnsSxMLLrviyfN1SAkylXTMd9AUp5Tp+Fl2cq9dQEzEp4/4aezLk7BsdguWehDEUaQhFbqbCYHdXnPYTDTP1dyMGbpt45TZ2/FRljwueq2CB4Y+7rGtQNmfqv2cs9JR89mp+G7HZzkK+twEfPaXqS/in0pg+nIgTH52sQo5NWnoc2CjaxbkXddscV9kiyc/iP6broaYVeD/WYPEyWbtIc8OOLPg=
deploy:
  provider: releases
  api_key:
    secure: dn1FtrJDobuvWfRudmE2Nz5feXVy/cALXtRfhvkF3qKjr4mTZ5ntOd0Dp5c+c8Zple8wvDauuWf8qhOfjkbVE6mDmdv3idqI05PNcS8Pazx6UBRvpeEWoCCUHpZg4ZCjQ0AwBiOl5E4jUr6iRUODtpkSnKLxOZO3Q4thmRJlc/E8AuST9+I2ClDkhrY7nujVb4/CmMr41RwaeprsfelHZUuSp+rePdgdWQN+MLe4IT8fATBi2Gin9EaGl57F535MGHpFTS8xBHEOx+RxVkCFT332Q1TkLBlnJz3xNvaHl0qikeOmUSEfD0nAT0uUxBkhH1yW3WlRk735fVmxU+57PV0kCn22CTgL5ZbG2+gT7mPy57eZ8VDLin1VRebH8BY1+JMRgkXy7bdt7EO/uYPbfjHatbsVQHIkxHmRgtimio+k6eaMP7Qv2t5VPNVTvRbjPNAzaTvZMkBSSnFiCpX1K/sISmXHBqDQPowNFPnEkEcAMMXiCK36TtWFxGfbzmyXjgoSGxH4QSoO8PXWUGj+z7kAyUr16e79GG3JJipigoYXhaSSGTO7I6WQTaNlkMewUMwRtxli1PWXYKScqtu/RQCm8PgzchP8YK0GoRFCZboCknixkNmeBBvx2h3yGy9IRb8VQLoxxL0fee8toqNsvMTG0Zw7iS2/MNpx5e+JzSg=
  file: build/libs/xltv-foodcritic-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xltv-foodcritic-plugin
